language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
<<<<<<< HEAD

=======
  
>>>>>>> branch '16_MVP' of https://github.com/Kantiran91/my-wachplan.git
script: phpunit --configuration phpunit.xml --coverage-text
