<?php
 /**
  * Kurze Beschreibung des Datei-Inhalts
  *
  * Lange Beschreibung des Datei-Inhaltes, wenn erforderlich.
  *
  * PHP versions 5
  *
  * LICENSE: This source file is subject CC BY 4.0 license
  *
  * @author  Sebastian Friedl <friedl.sebastian@web.de>
  * @license http://creativecommons.org/licenses/by/4.0/deed.en CC BY 4.0
  * @version GIT:  $Date$
  * @link    http:/salem.dlrg.de
  **/

class GlobalSettings
{
    const DISPLAYNAME = 'Globale Einstellungen';


    /**
     * Konstuktor.
     *
     * Siehe Klassenbeschreibung!
     */
    function __construct()
    {
        NULL;

    }//end __construct()

}//end class

?>